maplibre/maplibre-rs

docs/src/figures/README.md, docs/src/figures/maplibre-rs-2.svg, docs/src/figures/maplibre-rs-text.svg
Gear + MapLibre pushpin combined to form maplibre-rs logo.
Basic readme added to comply with rust logo license terms. Feel free to expand/replace as needed.
=> Maplibre rs logo

.cargo/config.toml
When I run the command `cargo run -p maplibre-demo` on my Mac (version 11.6.4), the target should be *x86_64-apple-darwin*. 
Because of the default config in `.cargo/config.toml` the target that is used instead is *x86_64-unknown-linux-gnu* and I get the error `error: failed to run custom build command for wayland-sys v0.29.4`.
I have looked at a few major Rust repositories and none seem to use a default cargo target.
I think we should remove the default build target so Rustup will use its active toolchain as shown by `rustup show`.
What do you think?
=> Remove the default build target in the Cargo configuration

.github/actions/android/action.yml
fixes #44 
We need to set the compiler and ar tool also for clippy. Previously it was only set during the `cargo build`.
=> Export toolchain tools

apple/xcode/maplibre-rs.xcodeproj/project.pbxproj
When we try to run the `./apple/xcode` project on a MacOS x86_64, the build fails because:
1. The build phases try to run cargo with a target of `x86_64-apple-ios-sim` but there is no `sim` target on x86_64. we need to build for x86_64 instead.
2. The library folder for architecture x86_64 - ios simulator was not set in the library search paths.
Additionally we can lower the iOS target version to version 9.
There have been two errors:
1. `Could not find specification for target "x86_64-apple-ios-sim"`
2. `libtool: can't locate file for: -lmaplibre_apple`
Open and run the iOS project with XCode on a Mac x86_64.
=> Improve apple iOS configuration

maplibre/src/context.rs, maplibre/src/coords.rs, maplibre/src/headless.rs, maplibre/src/map_schedule.rs, maplibre/src/render/camera.rs, maplibre/src/style/style.rs
Currently we only support a small subset of the [Mapbox Style Specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/root/). In the future, we would like to improve this support and to dynamically load styles from files.
\-
\-
=> Improve Mapbox Style support

README.md
Link to information on how to build for different platforms went to a 404. Changing to the current url.
=> Fix building guide link.

.github/workflows/on_main_push.yml
We do not use a .lock file, as maplibre is a library. Therefore, build could potentially fail if new updates to dependencies are pushed. By building maplibre scheduled we get to know that.
=> Run scheduled builds

maplibre-winit/src/input/pan_handler.rs, maplibre-winit/src/input/query_handler.rs, maplibre-winit/src/input/zoom_handler.rs, maplibre/src/context.rs, maplibre/src/render/camera.rs, maplibre/src/render/resource/buffer_pool.rs, maplibre/src/render/resource/mod.rs
This PR fixes an issue in which the znear value is taken into account when loading tiles.
I adjusted the znear and zfar. Indeed znear should be as large as possible. I added a reference link.
=> Avoid clipping in logic

maplibre/src/context.rs, maplibre/src/coords.rs, maplibre/src/render/stages/extract_stage.rs, maplibre/src/render/stages/resource_stage.rs, maplibre/src/render/stages/upload_stage.rs, maplibre/src/render/tile_view_pattern.rs, maplibre/src/stages/request_stage.rs
Previously we allowed infinitely many tiles in view. This caused buffer overflows.
This works around this issue:
```
thread 'main' panicked at 'Error in Queue::write_buffer: copy of 0..4216 would end up overrunning the bounds of the Destination buffer of size 2176'
```
=> Limit the tiles in view

.github/workflows/demo-macos.yml, .github/workflows/library-apple.yml
Updated to match the current version of the macOS runner now being macos-12:
https://github.blog/changelog/2022-06-13-github-actions-macos-12-for-github-hosted-runners-is-now-generally-available/
Action needs to be re-run through GitHub to check success.
- #27
=> Fixes #27 - switched to macos-12 runner which is GA since 2022-06-13

docs/src/development-guide/debugging.md, maplibre-demo/Cargo.toml, maplibre/Cargo.toml, maplibre/src/platform/noweb/mod.rs
Updated tracy dependencies to 0.8.1, with tracy-client to 0.14.* and tracing-tracy to 0.10.*
Re-run maplibre-demo without any additional errors.
- #138
=> Fixes #138 - upgraded tracy-client to 0.14.* and tracing-tracy to 0.10.*

maplibre-build-tools/src/wgsl.rs, maplibre/src/headless/map.rs, maplibre/src/io/geometry_index.rs, maplibre/src/io/tile_repository.rs, maplibre/src/kernel.rs, maplibre/src/platform/noweb/scheduler.rs, maplibre/src/render/builder.rs, maplibre/src/render/mod.rs, maplibre/src/render/resource/buffer_pool.rs, maplibre/src/util/fps_meter.rs
Fixes a number of clippy issues:
- Implement `Default` for various types
- Remove some useless format/mut
- Simplify some `if let match`
- Fix some cases where variables are never read because they are immediatly overwritten
=> Clippy fixes

justfile
This fixes an issue where `just web-lib build` would fail because it cannot find the 'core' crate.
I am not sure if this is the right way to fix the problem or the right place, but it worked for me.
```
$ just web-lib build
...
Creating WASM...
Compiling proc-macro2 v1.0.47
Compiling unicode-ident v1.0.5
Compiling quote v1.0.21
Compiling syn v1.0.103
Compiling autocfg v1.1.0
Compiling log v0.4.17
Compiling cfg-if v1.0.0
error[E0463]: can't find crate for `core`
|
= note: the `wasm32-unknown-unknown` target may not be installed
= help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
= help: consider building the standard library from source with `cargo build -Zbuild-std`
```
- Check the repo without any nightly rust toolchain installed on Ubuntu 22.04
- Run …
=> justfile: automatically install wasm32 target for nightly toolchain

.github/actions/install-system-dependencies/action.yml, .github/workflows/library-apple.yml, maplibre/Cargo.toml
The previous version (0.10.0) wouldn’t compile (rust 1.65, `cargo run -p maplibre-demo`, linux wayland) with the following error:
```
error[E0599]: no function or associated item named `decode` found for struct `Tile` in the current scope
--> maplibre/src/io/tile_pipelines.rs:28:40
|
28 |         let tile = geozero::mvt::Tile::decode(data.as_ref()).expect("failed to load tile");
|                                        ^^^^^^ function or associated item not found in `Tile`
|
= help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
|
1  | use prost::message::Message;
|
error: unused import: `prost::Message`
--> maplibre/src/io/tile_pipelines.rs:4:5
|
4  | use prost::Message;
| …
```
=> Bump prost crate version to 0.11.5

.github/actions/install-driver/action.yml, .github/actions/install-system-dependencies/action.yml, maplibre/src/io/source_client.rs, maplibre/src/io/transferables.rs, maplibre/src/render/render_commands.rs, maplibre/src/stages/populate_tile_store_stage.rs, web/src/platform/singlethreaded/transferables.rs
This fixes compatibility with my updated tileserver maps.tuerantuer.org
=> Tile source fixes

.github/actions/setup/action.yml, benchmarks/Cargo.toml, justfile
For the html reports, it now requires the cargo binary cargo-criterion.
Closes #216
=> Bump criterion to 0.4.0

maplibre/src/io/geometry_index.rs
see https://docs.rs/geo-types/latest/src/geo_types/geometry/coord.rs.html#33
=> use geo_types::Coord as geo_types::Coordinates is being deprecated

android/Cargo.toml, apple/Cargo.toml, maplibre-build-tools/Cargo.toml, maplibre-demo/Cargo.toml, maplibre/Cargo.toml
Edit: I had some weird troubles updating env_logger and clap on my computer. I had to `rm -r target` and rebuild from scratch. So at first I didn’t bump those, but there actually isn’t any problem.
I did not update:
* reqwest-middleware that changed its api
* rand that doesn’t seem to work with wasm target
=> Update trivial dependencies

maplibre/src/coords.rs, maplibre/src/render/render_commands.rs, maplibre/src/render/tile_view_pattern.rs
This pull request is more a question of style concerning `stencil_reference_value_2d` and `stencil_reference_value_3d`
The first commits changes a bit how the pattern matching is written. I believe it’s a bit more “rusty” and we have the guarantee the matching is complete.
The second commit moves those functions as a member of `WorldTileCoord` instead of `TileViewPattern`. I’m still missing the bigger picture of all those parts. The observation was that no information of `TileViewPattern` is required to do the computation, but I’ll perfectly understand that there are broader implications.
=> Simplify and move Stencil reference functions

maplibre/src/io/geometry_index.rs
This is a tiny improvement to the warnings to see which features are being used that we don't handle yet
=> Make warning more detailed

maplibre/src/headless/system.rs, maplibre/src/render/resource/surface.rs
Unwraps are bad, and we should gradually remove them (#92) 
This pull request removes them from a single function to see if we agree on how to do it.
The function now returns a Result (two specific errors have been created) and there still is an `expect`. So the in case of a failure, the program will still panic.
`cargo run -p maplibre-demo  --features headless -- headless`
It write 4 png on the current path
=> Remove unwrap from write_png

LICENSE-APACHE
This makes github detect license correctly.
Note that our Martin, as well as Rust lang itself has exactly this approach
| this is how github main pages looks at the moment (right side) |
|---|
| ![image](https://github.com/maplibre/maplibre-rs/assets/1641515/0166ee9c-9713-4ff1-8776-37e370ef2c45) |
=> Fix Apache license file

maplibre-build-tools/src/mbtiles.rs, maplibre-build-tools/src/wgsl.rs, maplibre-demo/src/headless.rs, maplibre/build.rs, maplibre/src/coords.rs, maplibre/src/headless/system.rs, maplibre/src/io/apc.rs, maplibre/src/io/static_tile_fetcher.rs, maplibre/src/platform/noweb/mod.rs, maplibre/src/raster/request_system.rs, maplibre/src/render/camera.rs, maplibre/src/render/eventually.rs, maplibre/src/render/graph/graph.rs, maplibre/src/render/resource/surface.rs, maplibre/src/render/resource/tracked_render_pass.rs, maplibre/src/render/systems/graph_runner_system.rs, maplibre/src/schedule.rs, maplibre/src/tcs/tiles.rs, maplibre/src/vector/process_vector.rs, maplibre/src/vector/render_commands.rs, maplibre/src/vector/request_system.rs, maplibre/src/vector/resource/buffer_pool.rs, maplibre/src/vector/upload_system.rs, maplibre/src/view_state.rs, web/src/platform/singlethreaded/apc.rs, web/src/platform/singlethreaded/wasm_entries.rs
a few minor inlining - it seems all tracing libs can handle inlined format args properly
NOTE: there are a few references that were passed to `format!`. I don't believe this is needed - format should work just as well with the actual value.  E.g. `format!("{}", foo)` and `format!("{}", &foo)` should be the same code.  See [stackoverflow](https://stackoverflow.com/questions/30450399/does-println-borrow-or-own-the-variable/30451360#30451360) that `foo` is already being passed in as `&foo`; so `&foo` is actually `&&foo`
=> chore: Inline format args

Cargo.toml, android/Cargo.toml, apple/Cargo.toml, benchmarks/Cargo.toml, maplibre-build-tools/Cargo.toml, maplibre-demo/Cargo.toml, maplibre-winit/Cargo.toml, maplibre/Cargo.toml, web/Cargo.toml
Move all dependencies to workspace so that we can keep all versions across packages in one spot.
Also add a geo keyword to the packagess.
See https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table
=> chore: Consolidate dependency version mgmt

Cargo.toml, justfile
Merge #281 first, before this one!!!
Bump most dependencies to the latest, except a few ones below.
=> chore: Bump consolidated dependencies

Cargo.toml, maplibre-winit/src/lib.rs, maplibre/src/window.rs
We did not use the initial scaling factor provided by winit.
=> Fix hidpi on web

web/lib/src/canvas.ts
This is required so we can use the right mouse to change pitch and yaw.
=> Disable right clicks on canvas

Cargo.toml, justfile, maplibre/src/platform/mod.rs, rust-toolchain.toml
Get the demo working again.
Let the example work.
```
cargo run -p maplibre-demo headed
```
Try running the current `main` branch (on a new environment) and then try this branch.
This is a different approach from https://github.com/maplibre/maplibre-rs/pull/299 but addresses the same issue.
=> Demo working again

README.md
Happy to report that it works in Safari Technology Preview now.
https://developer.apple.com/safari/technology-preview/
=> Update README to mention Safari TP

maplibre-winit/src/lib.rs, maplibre-winit/src/noweb.rs, maplibre/src/event_loop.rs
Fixes the annoying message in the dev console in browsers: Using exceptions for control flow, don't mind me.
=> Fix the control flow exception on web
