maplibre/maplibre-rs

.github/actions/android/action.yml

Disable clippy check on android

---

.github/ISSUE_TEMPLATE/Bug_Report.md
.github/ISSUE_TEMPLATE/Feature_Request.md
.github/ISSUE_TEMPLATE/RFC.md

Update issue templates

---

.github/actions/deploy/action.yml
.github/workflows/build-deploy-docs.yml
.github/workflows/library-web.yml

Fix deployment of docs, and disable of demo

---

.github/actions/cloudflare-deploy/action.yml
.github/actions/ssh-deploy/action.yml
.github/workflows/build-deploy-docs.yml
.github/workflows/library-web.yml
.github/workflows/on_main_push.yml
.github/workflows/on_pull_request.yml

Deploy to cloudflare

---

maplibre/Cargo.toml
maplibre/src/render/main_pass.rs
maplibre/src/render/mod.rs
maplibre/src/render/resource/pipeline.rs
maplibre/src/render/resource/shader.rs
maplibre/src/render/shaders/mod.rs

This fixes the compilation on the main branch.

Upgrade to wgpu 0.13

---

.idea/runConfigurations/Build_WASM.xml
justfile
rust-toolchain.toml

Update to 0.62.0 and latest nightly

Update rust toolchain version

---

benchmarks/benches/render.rs
maplibre-demo/Cargo.toml
maplibre-demo/src/main.rs
maplibre/src/context.rs
maplibre/src/coords.rs
maplibre/src/headless.rs
maplibre/src/lib.rs
maplibre/src/map_schedule.rs
maplibre/src/render/eventually.rs
maplibre/src/render/mod.rs
maplibre/src/render/render_commands.rs
maplibre/src/render/resource/buffer_pool.rs
maplibre/src/render/resource/surface.rs
maplibre/src/render/resource/texture.rs
maplibre/src/render/stages/extract_stage.rs
maplibre/src/render/stages/graph_runner_stage.rs
maplibre/src/render/stages/queue_stage.rs
maplibre/src/render/stages/upload_stage.rs
maplibre/src/util/math.rs

This changes a few things:
* Deduplicate code
* Actually make headless rendering working
* Move some files around
* Properly calculate camera height

Improve headless rendering

---

README.md

Add citation instructions

---

.github/workflows/library-web.yml
docs/src/development-guide/how-to-run.md
justfile
web/demo/package-lock.json
web/lib/@types/env/index.d.ts
web/lib/build.mjs
web/lib/package-lock.json
web/lib/package.json
web/lib/src/index.ts
web/lib/src/types.ts

This adds the command `just web-lib watch`
While running the demo this command can automatically update the library.

Add watch functionality for web

---

.idea/runConfigurations/Run_headed_demo__debug_enable_tracing_.xml
.idea/runConfigurations/Run_headed_demo__release_enable_tracing_.xml
maplibre-demo/Cargo.toml
maplibre-demo/src/headed.rs
maplibre-demo/src/headless.rs
maplibre-demo/src/main.rs
maplibre/src/context.rs
maplibre/src/coords.rs
maplibre/src/headless.rs
maplibre/src/io/tile_repository.rs
maplibre/src/map_schedule.rs
maplibre/src/style/style.rs

This add a simple CLI for the demo. Can be extended in the future.

Add CLI to demo

---

justfile

Choose toolchain depending on current arch.

Minor fix for macOS

---

.github/actions/cloudflare-deploy/action.yml

Right now wrangler does a preview deployment. Lets try to fix that.

Fix cloudflare production deployment

---

.github/actions/cargo-install/action.yml
.github/actions/setup-binstall/action.yml
.github/workflows/demo-windows.yml
benchmarks/benches/render.rs
justfile
maplibre/src/platform/mod.rs
maplibre/src/render/resource/globals.rs
maplibre/src/render/settings.rs
maplibre/src/render/stages/resource_stage.rs
maplibre/src/render/tile_pipeline.rs

* Switch to Depth32FloatStencil8 for support on metal. It seems to have better overall support.
* Fix some CI issues
* Switch to msys2 on windows

Use DEPTH32FLOAT_STENCIL8 for metal support

---

maplibre/Cargo.toml
maplibre/src/render/mod.rs
maplibre/src/render/settings.rs

Fixes the low-level stencil feature by upgrading wgpu: https://github.com/gfx-rs/wgpu/pull/3151

Fix stencil

---

.github/workflows/library-apple.yml
justfile
maplibre-winit/src/lib.rs
maplibre-winit/src/noweb.rs

This speeds up the CI for apple builds which take > 30min

Create a matrix job for apple

---

.github/actions/install-driver/action.yml
.github/workflows/demo-windows.yml
Cargo.toml
android/Cargo.toml
android/gradle/lib/build.gradle
apple/Cargo.toml
benchmarks/Cargo.toml
justfile
maplibre-build-tools/Cargo.toml
maplibre-demo/Cargo.toml
maplibre-winit/Cargo.toml
maplibre/Cargo.toml
rust-toolchain.toml
web/Cargo.toml

Update Rust version to be compatible with latest wgpu.
Switched now to stable and set a MSRV.

Update Rust for CI and IDEs

---

.github/workflows/demo-windows.yml

Experimentally switch to powershell and replace actions with powershell script.

Switch to powershell

---

web/demo/package-lock.json
web/demo/package.json
web/lib/package-lock.json
web/lib/package.json

This fixes a security warning.

Upgrade npm dependencies

---

maplibre/Cargo.toml
maplibre/src/platform/noweb/mod.rs

Else we might have two different versions of tracy in the project.

Fix tracy by using re-export

---

.github/actions/install-driver/action.yml
.github/workflows/build-deploy-docs.yml
.github/workflows/demo-linux.yml
.github/workflows/library-android.yml
.github/workflows/library-web.yml
.github/workflows/run-benchmarks.yml
.github/workflows/run-checks.yml
.github/workflows/run-tests.yml
maplibre/src/render/mod.rs

Ubuntu 20 might be not that well supported anymore. For example our graphics drivers for CI don't support 20 anymore: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

Upgrade to Ubuntu 22 in CI

---

.idea/runConfigurations/Run_demo__release_.xml
maplibre/src/io/tile_repository.rs
maplibre/src/render/render_commands.rs
maplibre/src/render/stages/extract_stage.rs
maplibre/src/render/stages/queue_stage.rs
maplibre/src/render/stages/upload_stage.rs
maplibre/src/style/layer.rs

Add code back which changes the color dynamically

---

maplibre/src/io/tile_pipelines.rs
maplibre/src/platform/noweb/mod.rs
maplibre/src/stages/populate_tile_store_stage.rs
maplibre/src/stages/request_stage.rs
maplibre/src/world.rs

Minor improvements in processing data.
Notably I changed `if` to while in this PR to reduce latency.

Improve processing

---

maplibre-build-tools/src/wgsl.rs
maplibre/src/headless/graph_node.rs
maplibre/src/headless/map.rs
maplibre/src/render/builder.rs
maplibre/src/render/resource/surface.rs

This fixes only the trivial ones. There are still other warnings, but they would require some deeper changes, so I prefer not to touch it, until I’m a bit more familiar with the code.

Apply some clippy hints

---

maplibre/Cargo.toml
maplibre/src/io/tile_pipelines.rs

@Tristramg this fixes the issue you discovered.

Use prost Message from geozero

---

maplibre/src/render/shaders/mod.rs
maplibre/src/render/shaders/tile_debug.vertex.wgsl

Debug line now have same pixel width

---

android/gradle/lib/build.gradle
justfile
rust-toolchain.toml

Upgrade Rust to nightly-2023-03-29 and 1.68

---

maplibre/src/render/shaders/tile.vertex.wgsl
maplibre/src/render/shaders/tile_debug.vertex.wgsl
maplibre/src/render/shaders/tile_mask.vertex.wgsl
maplibre/src/render/shaders/tile_raster.vertex.wgsl
shell.nix

Finally WebGPU is somewhat stable and our example runs in Chrome Beta 113!! Soon in stable chrome.

Fix shaders for Chrome 113

---

maplibre/Cargo.toml
maplibre/src/raster/upload_system.rs
maplibre/src/render/resource/surface.rs

See https://github.com/gfx-rs/wgpu/issues/3430

Upgrade to wgpu to fix issue on 0.15

---

maplibre/Cargo.toml

https://github.com/gfx-rs/wgpu/pull/3670

Fix webgpu demo 

---

maplibre/Cargo.toml

No changes needed as we targeted trunk before.

Update wgpu to 0.16

---

justfile

Run `just --fmt --unstable`
When reviewing, I suggest viewing it [without whitespace changes](https://github.com/maplibre/maplibre-rs/pull/280/files?diff=split&w=1)

Format justfile using just's own --fmt

---

Cargo.toml
android/Cargo.toml
android/gradle/.idea/gradle.xml
android/gradle/.idea/misc.xml
android/src/lib.rs
apple/MapLibreRs/Package.swift
apple/MapLibreRs/Sources/MapLibreRsExample/main.swift
apple/src/lib.rs
apple/xcode/maplibre-rs.xcodeproj/project.pbxproj
justfile
maplibre-demo/src/main.rs
maplibre-winit/Cargo.toml
maplibre-winit/src/lib.rs
maplibre-winit/src/noweb.rs
maplibre-winit/src/web.rs
maplibre/src/headless/mod.rs
maplibre/src/headless/window.rs
maplibre/src/kernel.rs
maplibre/src/map.rs
maplibre/src/render/mod.rs
maplibre/src/schedule.rs
maplibre/src/style/style.rs
maplibre/src/window.rs

Upgrade winit to window resizing on macOS and upgrade Android setup

---

web/demo/package-lock.json
web/demo/package.json
web/demo/webpack.config.ts
web/lib/build.mjs
web/lib/package-lock.json
web/lib/package.json

* Updated dependencies
* Removed watch mode because of esbuild update
* Set spectorjs to fixed version because of https://github.com/BabylonJS/Spector.js/issues/286

Update npm packages

---

.idea/runConfigurations/Run_demo__debug_.xml
.idea/runConfigurations/Run_demo__release_.xml
maplibre-winit/src/noweb.rs
maplibre/src/coords.rs
maplibre/src/io/geometry_index.rs
maplibre/src/raster/request_system.rs
maplibre/src/render/resource/tracked_render_pass.rs
maplibre/src/render/shaders/tile.vertex.wgsl
maplibre/src/render/shaders/tile_debug.vertex.wgsl
maplibre/src/render/shaders/tile_mask.vertex.wgsl
maplibre/src/render/shaders/tile_raster.vertex.wgsl
maplibre/src/render/systems/tile_view_pattern_system.rs
maplibre/src/render/tile_view_pattern/pattern.rs
web/src/lib.rs

This fixes the z-order. Also we filter duplicates in the view region pattern to improve render performance.

Render fixes

---

maplibre-winit/src/input/mod.rs
maplibre-winit/src/lib.rs
maplibre-winit/src/noweb.rs
maplibre-winit/src/web.rs
maplibre/src/context.rs
maplibre/src/headless/mod.rs
maplibre/src/headless/window.rs
maplibre/src/render/mod.rs
maplibre/src/render/resource/surface.rs
maplibre/src/render/view_state.rs
maplibre/src/window.rs

This is only a WIP, but it is needed for any HiDPI displays to achive reasonable performance.

Initial support for hidpi

---

.github/workflows/library-android.yml
.github/workflows/library-web.yml
Cargo.toml
android/gradle/lib/build.gradle
justfile
maplibre/src/debug/debug_pass.rs
maplibre/src/render/camera.rs
maplibre/src/render/error.rs
maplibre/src/render/main_pass.rs
maplibre/src/render/mod.rs
shell.nix
web/src/platform/http_client.rs
web/src/platform/multithreaded/pool_scheduler.rs
web/src/platform/singlethreaded/wasm_entries.rs

This should fix:
* NDK version
* version of wasm-bindgen
* fix the nix-shell for usage on Nix

Fix builds

---

Cargo.toml
android/src/lib.rs
apple/src/lib.rs
maplibre-demo/src/main.rs
maplibre-winit/src/lib.rs
maplibre-winit/src/noweb.rs
maplibre/Cargo.toml
maplibre/src/environment.rs
maplibre/src/headless/mod.rs
maplibre/src/io/apc.rs
maplibre/src/platform/noweb/http_client.rs
maplibre/src/platform/noweb/mod.rs
maplibre/src/raster/request_system.rs
maplibre/src/vector/request_system.rs
shell.nix
web/lib/build.mjs
web/lib/src/index.ts
web/lib/src/multithreaded/multithreaded-pool.worker.ts
web/lib/src/singlethreaded/pool.worker.ts
web/src/lib.rs
web/src/platform/multithreaded/pool.rs
web/src/platform/multithreaded/wasm_entries.rs
web/src/platform/singlethreaded/apc.rs
web/src/platform/singlethreaded/wasm_entries.rs

This adds a config to the offscreen. WIP for web. Basically we need somehow to send configuration data from the main thread to the worker threads.

Improve and fix http cache & add offscreen kernel config

---

README.md

Document minimum Safari version

---

maplibre-winit/src/lib.rs

Fixes https://github.com/maplibre/maplibre-rs/issues/274

Handle zero width or height

---

README.md

fix the smelling of lingua franca

very small spelling correction

---

android/gradle/lib/build.gradle

Update ndk version

---

.github/FUNDING.yml
CODE-OF-CONDUCT.md
README.md

Few missing steps from the onboarding [checklist](https://github.com/maplibre/maplibre/issues/24)
- slack channel link
- funding links
- code of conduct

Onboarding checklist
